<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
					</button>
					<h1>
						<a class="navbar-brand" href="./"><img class="navbar-brand" src="images/logo.png" alt="<?php echo $parentTitle;?>"></a>
					</h1>
				</div>
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="spiderman.php">Spider-Man</a></li>
						<li><a href="greenlantern.php">Green Lantern</a></li>
						<li><a href="thor.php">Thor</a></li>
						<li><a href="colophon.php">Colophon</a></li>
					</ul>
				</div>
			</div>
		</nav>
