<div class="container">
	<br>
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<ol class ="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"</li>
		<li data-target="#myCarousel" data-slide-to="1"</li>
		<li data-target="#myCarousel" data-slide-to="2"</li>
		<li data-target="#myCarousel" data-slide-to="3"</li>
	</ol>

	<div class = "carousel-inner" role="listbox">
		<div class = "item active">
			<img src="sipdey.jpg" alt="Spiderman" width="460" height="345">
		</div>
		<div class = "item">
			<img src="green.jpg" alt="GreenLantern" width="460" height="345">
		</div>
		<div class = "item">
			<img src="thor.jpg" alt="Thor" width="460" height="345">
		</div>
	</div>

	<a class= "left carousel-control" href="#myCarousel" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
	</div>
</div>
