<!doctype html>
<html lang = "en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>
<?php
$pagename = basename($_SERVER['PHP_SELF']);
echo basename($pagename, ".php");
?>
	</title>
	
	<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <link rel="stylesheet" href="css/side-menu.css">
    <link href="https://fonts.googleapis.com/css?family=Cuprum" rel="stylesheet">

</head>

<body id="layout">
